/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_Fmod_InitDynJNI */

#ifndef _Included_org_jouvieje_Fmod_InitDynJNI
#define _Included_org_jouvieje_Fmod_InitDynJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_Fmod_InitDynJNI
 * Method:    attachJavaVM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_InitDynJNI_attachJavaVM
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
