/* DO NOT EDIT THIS FILE - it is machine generated */
#include "Includes.h"
/* Header for class org_jouvieje_FmodDyn_FmodDynJNI */

#ifndef _Included_org_jouvieje_FmodDyn_FmodDynJNI
#define _Included_org_jouvieje_FmodDyn_FmodDynJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_CreateInstance
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1CreateInstance
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_FreeInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1FreeInstance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetOutput
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetOutput
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetDriver
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetDriver
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetMixer
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetMixer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetBufferSize
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetBufferSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetHWND
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetHWND
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetMinHardwareChannels
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetMinHardwareChannels
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetMaxHardwareChannels
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetMaxHardwareChannels
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetMemorySystem
 * Signature: (JLjava/nio/ByteBuffer;IILorg/jouvieje/Fmod/Callbacks/FSOUND_ALLOCCALLBACK;Lorg/jouvieje/Fmod/Callbacks/FSOUND_REALLOCCALLBACK;Lorg/jouvieje/Fmod/Callbacks/FSOUND_FREECALLBACK;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetMemorySystem
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jobject, jobject, jobject);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Init
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Init
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Update
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Update
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetSpeakerMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetSpeakerMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetSFXMasterVolume
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetSFXMasterVolume
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetPanSeperation
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetPanSeperation
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_File_SetCallbacks
 * Signature: (JLorg/jouvieje/Fmod/Callbacks/FSOUND_OPENCALLBACK;Lorg/jouvieje/Fmod/Callbacks/FSOUND_CLOSECALLBACK;Lorg/jouvieje/Fmod/Callbacks/FSOUND_READCALLBACK;Lorg/jouvieje/Fmod/Callbacks/FSOUND_SEEKCALLBACK;Lorg/jouvieje/Fmod/Callbacks/FSOUND_TELLCALLBACK;)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1File_1SetCallbacks
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetError
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetVersion
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetOutput
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetOutput
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetOutputHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetOutputHandle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetDriver
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetDriver
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetMixer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetMixer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetNumDrivers
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetNumDrivers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetDriverName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetDriverName
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetDriverCaps
 * Signature: (JI[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetDriverCaps__JI_3I
  (JNIEnv *, jclass, jlong, jint, jintArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetDriverCaps
 * Signature: (JILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetDriverCaps__JILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetOutputRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetOutputRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetMaxChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetMaxChannels
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetMaxSamples
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetMaxSamples
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetSpeakerMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetSpeakerMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetSFXMasterVolume
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetSFXMasterVolume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetNumHWChannels
 * Signature: (J[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetNumHWChannels__J_3I_3I_3I
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetNumHWChannels
 * Signature: (JLjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetNumHWChannels__JLjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetChannelsPlaying
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetChannelsPlaying
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetCPUUsage
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetCPUUsage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetMemoryStats
 * Signature: (J[I[I)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetMemoryStats__J_3I_3I
  (JNIEnv *, jclass, jlong, jintArray, jintArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetMemoryStats
 * Signature: (JLjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetMemoryStats__JLjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_Load
 * Signature: (JILjava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1Load__JILjava_lang_String_2III
  (JNIEnv *, jclass, jlong, jint, jstring, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_Load
 * Signature: (JILjava/nio/ByteBuffer;IIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1Load__JILjava_nio_ByteBuffer_2IIII
  (JNIEnv *, jclass, jlong, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_Alloc
 * Signature: (JIIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1Alloc
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_Free
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1Free
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_Upload
 * Signature: (JJLjava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1Upload
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_Lock
 * Signature: (JJIILorg/jouvieje/Fmod/Misc/Pointer;Lorg/jouvieje/Fmod/Misc/Pointer;[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1Lock__JJIILorg_jouvieje_Fmod_Misc_Pointer_2Lorg_jouvieje_Fmod_Misc_Pointer_2_3I_3I
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jobject, jobject, jintArray, jintArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_Lock
 * Signature: (JJIILorg/jouvieje/Fmod/Misc/Pointer;Lorg/jouvieje/Fmod/Misc/Pointer;Ljava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1Lock__JJIILorg_jouvieje_Fmod_Misc_Pointer_2Lorg_jouvieje_Fmod_Misc_Pointer_2Ljava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jobject, jobject, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_Unlock
 * Signature: (JJJJII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1Unlock__JJJJII
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_Unlock
 * Signature: (JJLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1Unlock__JJLjava_nio_ByteBuffer_2ILjava_nio_ByteBuffer_2III
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jobject, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_SetMode
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1SetMode
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_SetLoopPoints
 * Signature: (JJII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1SetLoopPoints
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_SetDefaults
 * Signature: (JJIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1SetDefaults
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_SetDefaultsEx
 * Signature: (JJIIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1SetDefaultsEx
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_SetMinMaxDistance
 * Signature: (JJFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1SetMinMaxDistance
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_SetMaxPlaybacks
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1SetMaxPlaybacks
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_Get
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1Get
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_GetName
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1GetName
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_GetLength
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1GetLength
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_GetLoopPoints
 * Signature: (JJ[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1GetLoopPoints__JJ_3I_3I
  (JNIEnv *, jclass, jlong, jlong, jintArray, jintArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_GetLoopPoints
 * Signature: (JJLjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1GetLoopPoints__JJLjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_GetDefaults
 * Signature: (JJ[I[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1GetDefaults__JJ_3I_3I_3I_3I
  (JNIEnv *, jclass, jlong, jlong, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_GetDefaults
 * Signature: (JJLjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1GetDefaults__JJLjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_GetDefaultsEx
 * Signature: (JJ[I[I[I[I[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1GetDefaultsEx__JJ_3I_3I_3I_3I_3I_3I_3I
  (JNIEnv *, jclass, jlong, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_GetDefaultsEx
 * Signature: (JJLjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1GetDefaultsEx__JJLjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_GetMode
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1GetMode
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_GetMinMaxDistance
 * Signature: (JJ[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1GetMinMaxDistance__JJ_3F_3F
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jfloatArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Sample_GetMinMaxDistance
 * Signature: (JJLjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Sample_1GetMinMaxDistance__JJLjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_PlaySound
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1PlaySound
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_PlaySoundEx
 * Signature: (JIJJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1PlaySoundEx
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_StopSound
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1StopSound
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetFrequency
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetFrequency
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetVolume
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetVolume
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetVolumeAbsolute
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetVolumeAbsolute
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetPan
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetPan
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetSurround
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetSurround
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetMute
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetMute
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetPriority
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetPriority
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetReserved
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetReserved
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetPaused
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetPaused
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetLoopMode
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetLoopMode
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_SetCurrentPosition
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1SetCurrentPosition
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_SetAttributes
 * Signature: (JI[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1SetAttributes__JI_3F_3F
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jfloatArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_SetAttributes
 * Signature: (JILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1SetAttributes__JILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jlong, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_SetMinMaxDistance
 * Signature: (JIFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1SetMinMaxDistance
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_IsPlaying
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1IsPlaying
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetFrequency
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetFrequency
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetVolume
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetVolume
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetAmplitude
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetAmplitude
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetPan
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetPan
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetSurround
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetSurround
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetMute
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetMute
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetPriority
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetPriority
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetReserved
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetReserved
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetPaused
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetPaused
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetLoopMode
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetLoopMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetCurrentPosition
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetCurrentPosition
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetCurrentSample
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetCurrentSample
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetCurrentLevels
 * Signature: (JI[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetCurrentLevels__JI_3F_3F
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jfloatArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetCurrentLevels
 * Signature: (JILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetCurrentLevels__JILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jlong, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetNumSubChannels
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetNumSubChannels
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_GetSubChannel
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1GetSubChannel
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_GetAttributes
 * Signature: (JI[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1GetAttributes__JI_3F_3F
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jfloatArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_GetAttributes
 * Signature: (JILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1GetAttributes__JILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jlong, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_GetMinMaxDistance
 * Signature: (JI[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1GetMinMaxDistance__JI_3F_3F
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jfloatArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_GetMinMaxDistance
 * Signature: (JILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1GetMinMaxDistance__JILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jlong, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_SetDopplerFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1SetDopplerFactor
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_SetDistanceFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1SetDistanceFactor
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_SetRolloffFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1SetRolloffFactor
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_Listener_SetCurrent
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1Listener_1SetCurrent
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_Listener_SetAttributes
 * Signature: (J[F[FFFFFFF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1Listener_1SetAttributes__J_3F_3FFFFFFF
  (JNIEnv *, jclass, jlong, jfloatArray, jfloatArray, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_Listener_SetAttributes
 * Signature: (JLjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;IFFFFFF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1Listener_1SetAttributes__JLjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2IFFFFFF
  (JNIEnv *, jclass, jlong, jobject, jint, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_Listener_GetAttributes
 * Signature: (J[F[F[F[F[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1Listener_1GetAttributes__J_3F_3F_3F_3F_3F_3F_3F_3F
  (JNIEnv *, jclass, jlong, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_3D_Listener_GetAttributes
 * Signature: (JLjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_13D_1Listener_1GetAttributes__JLjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jlong, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_FX_Enable
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1FX_1Enable
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_FX_Disable
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1FX_1Disable
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_FX_SetChorus
 * Signature: (JIFFFFIFI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1FX_1SetChorus
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_FX_SetCompressor
 * Signature: (JIFFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1FX_1SetCompressor
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_FX_SetDistortion
 * Signature: (JIFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1FX_1SetDistortion
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_FX_SetEcho
 * Signature: (JIFFFFZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1FX_1SetEcho
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_FX_SetFlanger
 * Signature: (JIFFFFIFI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1FX_1SetFlanger
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_FX_SetGargle
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1FX_1SetGargle
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_FX_SetI3DL2Reverb
 * Signature: (JIIIFFFIFIFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1FX_1SetI3DL2Reverb
  (JNIEnv *, jclass, jlong, jint, jint, jint, jfloat, jfloat, jfloat, jint, jfloat, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_FX_SetParamEQ
 * Signature: (JIFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1FX_1SetParamEQ
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_FX_SetWavesReverb
 * Signature: (JIFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1FX_1SetWavesReverb
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_SetBufferSize
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1SetBufferSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Open
 * Signature: (JLjava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Open__JLjava_lang_String_2III
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Open
 * Signature: (JLjava/nio/ByteBuffer;IIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Open__JLjava_nio_ByteBuffer_2IIII
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Create
 * Signature: (JLorg/jouvieje/Fmod/Callbacks/FSOUND_STREAMCALLBACK;IIIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Create
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jint, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Close
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Close
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Play
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Play
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_PlayEx
 * Signature: (JIJJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1PlayEx
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Stop
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Stop
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_SetPosition
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1SetPosition
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetPosition
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetPosition
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_SetTime
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1SetTime
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetTime
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetTime
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetLength
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetLength
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetLengthMs
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetLengthMs
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_SetMode
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1SetMode
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetMode
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetMode
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_SetLoopPoints
 * Signature: (JJII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1SetLoopPoints
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_SetLoopCount
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1SetLoopCount
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetOpenState
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetOpenState
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetSample
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetSample
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_CreateDSP
 * Signature: (JJLorg/jouvieje/Fmod/Callbacks/FSOUND_DSPCALLBACK;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1CreateDSP
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_SetEndCallback
 * Signature: (JJLorg/jouvieje/Fmod/Callbacks/FSOUND_STREAMCALLBACK;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1SetEndCallback
  (JNIEnv *, jclass, jlong, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_SetSyncCallback
 * Signature: (JJLorg/jouvieje/Fmod/Callbacks/FSOUND_STREAMCALLBACK;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1SetSyncCallback
  (JNIEnv *, jclass, jlong, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_AddSyncPoint
 * Signature: (JJILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1AddSyncPoint
  (JNIEnv *, jclass, jlong, jlong, jint, jstring);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_DeleteSyncPoint
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1DeleteSyncPoint
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetNumSyncPoints
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetNumSyncPoints
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetSyncPoint
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetSyncPoint
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetSyncPointInfo
 * Signature: (JJ[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetSyncPointInfo__JJ_3I
  (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetSyncPointInfo
 * Signature: (JJLjava/nio/IntBuffer;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetSyncPointInfo__JJLjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jlong, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_SetSubStream
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1SetSubStream
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetNumSubStreams
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetNumSubStreams
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_SetSubStreamSentence
 * Signature: (JJ[II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1SetSubStreamSentence__JJ_3II
  (JNIEnv *, jclass, jlong, jlong, jintArray, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_SetSubStreamSentence
 * Signature: (JJLjava/nio/IntBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1SetSubStreamSentence__JJLjava_nio_IntBuffer_2II
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetNumTagFields
 * Signature: (JJ[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetNumTagFields__JJ_3I
  (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetNumTagFields
 * Signature: (JJLjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetNumTagFields__JJLjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jlong, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetTagField
 * Signature: (JJI[ILorg/jouvieje/Fmod/Misc/Pointer;Lorg/jouvieje/Fmod/Misc/Pointer;[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetTagField__JJI_3ILorg_jouvieje_Fmod_Misc_Pointer_2Lorg_jouvieje_Fmod_Misc_Pointer_2_3I
  (JNIEnv *, jclass, jlong, jlong, jint, jintArray, jobject, jobject, jintArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_GetTagField
 * Signature: (JJILjava/nio/IntBuffer;ILorg/jouvieje/Fmod/Misc/Pointer;Lorg/jouvieje/Fmod/Misc/Pointer;Ljava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1GetTagField__JJILjava_nio_IntBuffer_2ILorg_jouvieje_Fmod_Misc_Pointer_2Lorg_jouvieje_Fmod_Misc_Pointer_2Ljava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jlong, jint, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_FindTagField
 * Signature: (JJILjava/lang/String;Lorg/jouvieje/Fmod/Misc/Pointer;[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1FindTagField__JJILjava_lang_String_2Lorg_jouvieje_Fmod_Misc_Pointer_2_3I
  (JNIEnv *, jclass, jlong, jlong, jint, jstring, jobject, jintArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_FindTagField
 * Signature: (JJILjava/lang/String;Lorg/jouvieje/Fmod/Misc/Pointer;Ljava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1FindTagField__JJILjava_lang_String_2Lorg_jouvieje_Fmod_Misc_Pointer_2Ljava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jlong, jint, jstring, jobject, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Net_SetProxy
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Net_1SetProxy
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FSOUND_Stream_Net_SetTimeout
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FSOUND_1Stream_1Net_1SetTimeout
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Net_GetLastServerStatus
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Net_1GetLastServerStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Net_SetBufferProperties
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Net_1SetBufferProperties
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Net_GetBufferProperties
 * Signature: (J[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Net_1GetBufferProperties__J_3I_3I_3I
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Net_GetBufferProperties
 * Signature: (JLjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Net_1GetBufferProperties__JLjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Net_SetMetadataCallback
 * Signature: (JJLorg/jouvieje/Fmod/Callbacks/FSOUND_METADATACALLBACK;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Net_1SetMetadataCallback
  (JNIEnv *, jclass, jlong, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Net_GetStatus
 * Signature: (JJ[I[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Net_1GetStatus__JJ_3I_3I_3I_3I
  (JNIEnv *, jclass, jlong, jlong, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Stream_Net_GetStatus
 * Signature: (JJLjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Stream_1Net_1GetStatus__JJLjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_Play
 * Signature: (JCI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1Play
  (JNIEnv *, jclass, jlong, jchar, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_SetPlayMode
 * Signature: (JCB)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1SetPlayMode
  (JNIEnv *, jclass, jlong, jchar, jbyte);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_Stop
 * Signature: (JC)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1Stop
  (JNIEnv *, jclass, jlong, jchar);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_SetPaused
 * Signature: (JCZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1SetPaused
  (JNIEnv *, jclass, jlong, jchar, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_SetVolume
 * Signature: (JCI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1SetVolume
  (JNIEnv *, jclass, jlong, jchar, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_SetTrackTime
 * Signature: (JCI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1SetTrackTime
  (JNIEnv *, jclass, jlong, jchar, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_Eject
 * Signature: (JC)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1Eject
  (JNIEnv *, jclass, jlong, jchar);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_OpenTray
 * Signature: (JCZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1OpenTray
  (JNIEnv *, jclass, jlong, jchar, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_GetPaused
 * Signature: (JC)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1GetPaused
  (JNIEnv *, jclass, jlong, jchar);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_GetTrack
 * Signature: (JC)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1GetTrack
  (JNIEnv *, jclass, jlong, jchar);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_GetNumTracks
 * Signature: (JC)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1GetNumTracks
  (JNIEnv *, jclass, jlong, jchar);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_GetVolume
 * Signature: (JC)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1GetVolume
  (JNIEnv *, jclass, jlong, jchar);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_GetTrackLength
 * Signature: (JCI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1GetTrackLength
  (JNIEnv *, jclass, jlong, jchar, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_CD_GetTrackTime
 * Signature: (JC)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1CD_1GetTrackTime
  (JNIEnv *, jclass, jlong, jchar);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_Create
 * Signature: (JLorg/jouvieje/Fmod/Callbacks/FSOUND_DSPCALLBACK;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1Create
  (JNIEnv *, jclass, jlong, jobject, jint, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_Free
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1Free
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_SetPriority
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1SetPriority
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_GetPriority
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1GetPriority
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_SetActive
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1SetActive
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_GetActive
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1GetActive
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_GetClearUnit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1GetClearUnit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_GetSFXUnit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1GetSFXUnit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_GetMusicUnit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1GetMusicUnit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_GetFFTUnit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1GetFFTUnit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_GetClipAndCopyUnit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1GetClipAndCopyUnit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_MixBuffers
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1MixBuffers
  (JNIEnv *, jclass, jlong, jobject, jint, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_ClearMixBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1ClearMixBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_GetBufferLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1GetBufferLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_GetBufferLengthTotal
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1GetBufferLengthTotal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_DSP_GetSpectrum
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1DSP_1GetSpectrum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Reverb_SetProperties
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Reverb_1SetProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Reverb_GetProperties
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Reverb_1GetProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Reverb_SetChannelProperties
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Reverb_1SetChannelProperties
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Reverb_GetChannelProperties
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Reverb_1GetChannelProperties
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Record_SetDriver
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Record_1SetDriver
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Record_GetNumDrivers
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Record_1GetNumDrivers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Record_GetDriverName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Record_1GetDriverName
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Record_GetDriver
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Record_1GetDriver
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Record_StartSample
 * Signature: (JJZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Record_1StartSample
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Record_Stop
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Record_1Stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FSOUND_Record_GetPosition
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FSOUND_1Record_1GetPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_LoadSong
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1LoadSong
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_LoadSongEx
 * Signature: (JLjava/lang/String;III[II)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1LoadSongEx__JLjava_lang_String_2III_3II
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jintArray, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_LoadSongEx
 * Signature: (JLjava/nio/ByteBuffer;IIII[II)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1LoadSongEx__JLjava_nio_ByteBuffer_2IIII_3II
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jint, jint, jintArray, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_LoadSongEx
 * Signature: (JLjava/lang/String;IIILjava/nio/IntBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1LoadSongEx__JLjava_lang_String_2IIILjava_nio_IntBuffer_2II
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_LoadSongEx
 * Signature: (JLjava/nio/ByteBuffer;IIIILjava/nio/IntBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1LoadSongEx__JLjava_nio_ByteBuffer_2IIIILjava_nio_IntBuffer_2II
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetOpenState
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetOpenState
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_FreeSong
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1FreeSong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_PlaySong
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1PlaySong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_StopSong
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1StopSong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_StopAllSongs
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1StopAllSongs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_SetZxxCallback
 * Signature: (JJLorg/jouvieje/Fmod/Callbacks/FMUSIC_CALLBACK;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1SetZxxCallback
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_SetRowCallback
 * Signature: (JJLorg/jouvieje/Fmod/Callbacks/FMUSIC_CALLBACK;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1SetRowCallback
  (JNIEnv *, jclass, jlong, jlong, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_SetOrderCallback
 * Signature: (JJLorg/jouvieje/Fmod/Callbacks/FMUSIC_CALLBACK;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1SetOrderCallback
  (JNIEnv *, jclass, jlong, jlong, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_SetInstCallback
 * Signature: (JJLorg/jouvieje/Fmod/Callbacks/FMUSIC_CALLBACK;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1SetInstCallback
  (JNIEnv *, jclass, jlong, jlong, jobject, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_SetSample
 * Signature: (JJIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1SetSample
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_SetUserData
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1SetUserData
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_OptimizeChannels
 * Signature: (JJII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1OptimizeChannels
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_SetReverb
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1SetReverb
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_SetLooping
 * Signature: (JJZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1SetLooping
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_SetOrder
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1SetOrder
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_SetPaused
 * Signature: (JJZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1SetPaused
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_SetMasterVolume
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1SetMasterVolume
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_SetMasterSpeed
 * Signature: (JJF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1SetMasterSpeed
  (JNIEnv *, jclass, jlong, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_SetPanSeperation
 * Signature: (JJF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1SetPanSeperation
  (JNIEnv *, jclass, jlong, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetName
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetName
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetType
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetType
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetNumOrders
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetNumOrders
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetNumPatterns
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetNumPatterns
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetNumInstruments
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetNumInstruments
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetNumSamples
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetNumSamples
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetNumChannels
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetNumChannels
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetSample
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetSample
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetPatternLength
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetPatternLength
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_IsFinished
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1IsFinished
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_IsPlaying
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1IsPlaying
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetMasterVolume
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetMasterVolume
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetGlobalVolume
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetGlobalVolume
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetOrder
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetOrder
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetPattern
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetPattern
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetSpeed
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetSpeed
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetBPM
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetBPM
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetRow
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetRow
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetPaused
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetPaused
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetTime
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetTime
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetRealChannel
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetRealChannel
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDyn_FmodDynJNI
 * Method:    FMOD_INSTANCE_FMUSIC_GetUserData
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDyn_FmodDynJNI_FMOD_1INSTANCE_1FMUSIC_1GetUserData
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
