/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_Fmod_Enumerations_EnumerationJNI */

#ifndef _Included_org_jouvieje_Fmod_Enumerations_EnumerationJNI
#define _Included_org_jouvieje_Fmod_Enumerations_EnumerationJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1NONE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_BUSY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1BUSY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_UNINITIALIZED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1UNINITIALIZED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_INIT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1INIT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_ALLOCATED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1ALLOCATED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_PLAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1PLAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_OUTPUT_FORMAT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1OUTPUT_1FORMAT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_COOPERATIVELEVEL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1COOPERATIVELEVEL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_CREATEBUFFER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1CREATEBUFFER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_FILE_NOTFOUND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1FILE_1NOTFOUND
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_FILE_FORMAT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1FILE_1FORMAT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_FILE_BAD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1FILE_1BAD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_MEMORY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1MEMORY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_VERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1VERSION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_INVALID_PARAM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1INVALID_1PARAM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_NO_EAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1NO_1EAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_CHANNEL_ALLOC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1CHANNEL_1ALLOC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_RECORD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1RECORD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_MEDIAPLAYER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1MEDIAPLAYER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_CDDEVICE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1CDDEVICE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMUSIC_TYPE_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMUSIC_1TYPE_1NONE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMUSIC_TYPE_MOD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMUSIC_1TYPE_1MOD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMUSIC_TYPE_S3M
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMUSIC_1TYPE_1S3M
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMUSIC_TYPE_XM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMUSIC_1TYPE_1XM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMUSIC_TYPE_IT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMUSIC_1TYPE_1IT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMUSIC_TYPE_MIDI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMUSIC_1TYPE_1MIDI
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FMUSIC_TYPE_FSB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FMUSIC_1TYPE_1FSB
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_MIXER_AUTODETECT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1MIXER_1AUTODETECT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_MIXER_QUALITY_AUTODETECT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1MIXER_1QUALITY_1AUTODETECT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_MIXER_QUALITY_FPU
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1MIXER_1QUALITY_1FPU
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_MIXER_QUALITY_MMXP5
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1MIXER_1QUALITY_1MMXP5
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_MIXER_QUALITY_MMXP6
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1MIXER_1QUALITY_1MMXP6
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_MIXER_MONO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1MIXER_1MONO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_MIXER_QUALITY_MONO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1MIXER_1QUALITY_1MONO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_MIXER_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1MIXER_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_NOSOUND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1NOSOUND
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_WINMM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1WINMM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_DSOUND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1DSOUND
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_A3D
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1A3D
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_OSS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1OSS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_ESD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1ESD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_ALSA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1ALSA
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_ASIO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1ASIO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_XBOX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1XBOX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_PS2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1PS2
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_MAC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1MAC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_GC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1GC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_PSP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1PSP
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_OUTPUT_NOSOUND_NONREALTIME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1OUTPUT_1NOSOUND_1NONREALTIME
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_SPEAKERMODE_DOLBYDIGITAL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1SPEAKERMODE_1DOLBYDIGITAL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_SPEAKERMODE_HEADPHONES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1SPEAKERMODE_1HEADPHONES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_SPEAKERMODE_MONO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1SPEAKERMODE_1MONO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_SPEAKERMODE_QUAD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1SPEAKERMODE_1QUAD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_SPEAKERMODE_STEREO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1SPEAKERMODE_1STEREO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_SPEAKERMODE_SURROUND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1SPEAKERMODE_1SURROUND
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_SPEAKERMODE_DTS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1SPEAKERMODE_1DTS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_SPEAKERMODE_PROLOGIC2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1SPEAKERMODE_1PROLOGIC2
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_SPEAKERMODE_PROLOGIC2_INTERIOR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1SPEAKERMODE_1PROLOGIC2_1INTERIOR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_STREAM_NET_NOTCONNECTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1STREAM_1NET_1NOTCONNECTED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_STREAM_NET_CONNECTING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1STREAM_1NET_1CONNECTING
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_STREAM_NET_BUFFERING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1STREAM_1NET_1BUFFERING
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_STREAM_NET_READY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1STREAM_1NET_1READY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_STREAM_NET_ERROR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1STREAM_1NET_1ERROR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_TAGFIELD_VORBISCOMMENT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1TAGFIELD_1VORBISCOMMENT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_TAGFIELD_ID3V1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1TAGFIELD_1ID3V1
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_TAGFIELD_ID3V2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1TAGFIELD_1ID3V2
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_TAGFIELD_SHOUTCAST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1TAGFIELD_1SHOUTCAST
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_TAGFIELD_ICECAST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1TAGFIELD_1ICECAST
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_TAGFIELD_ASF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1TAGFIELD_1ASF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_FX_CHORUS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1FX_1CHORUS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_FX_COMPRESSOR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1FX_1COMPRESSOR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_FX_DISTORTION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1FX_1DISTORTION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_FX_ECHO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1FX_1ECHO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_FX_FLANGER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1FX_1FLANGER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_FX_GARGLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1FX_1GARGLE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_FX_I3DL2REVERB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1FX_1I3DL2REVERB
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_FX_PARAMEQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1FX_1PARAMEQ
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_FX_WAVES_REVERB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1FX_1WAVES_1REVERB
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Enumerations_EnumerationJNI
 * Method:    get_FSOUND_FX_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Enumerations_EnumerationJNI_get_1FSOUND_1FX_1MAX
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
