/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_Fmod_Structures_StructureJNI */

#ifndef _Included_org_jouvieje_Fmod_Structures_StructureJNI
#define _Included_org_jouvieje_Fmod_Structures_StructureJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_Environment
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1Environment
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_Environment
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1Environment
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_EnvSize
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1EnvSize
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_EnvSize
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1EnvSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_EnvDiffusion
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1EnvDiffusion
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_EnvDiffusion
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1EnvDiffusion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_Room
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1Room
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_Room
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1Room
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_RoomHF
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1RoomHF
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_RoomHF
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1RoomHF
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_RoomLF
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1RoomLF
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_RoomLF
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1RoomLF
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_DecayTime
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1DecayTime
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_DecayTime
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1DecayTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_DecayHFRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1DecayHFRatio
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_DecayHFRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1DecayHFRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_DecayLFRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1DecayLFRatio
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_DecayLFRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1DecayLFRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_Reflections
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1Reflections
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_Reflections
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1Reflections
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_ReflectionsDelay
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1ReflectionsDelay
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_ReflectionsDelay
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1ReflectionsDelay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_ReflectionsPan
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1ReflectionsPan
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_ReflectionsPan
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1ReflectionsPan
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_Reverb
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1Reverb
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_Reverb
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1Reverb
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_ReverbDelay
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1ReverbDelay
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_ReverbDelay
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1ReverbDelay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_ReverbPan
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1ReverbPan
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_ReverbPan
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1ReverbPan
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_EchoTime
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1EchoTime
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_EchoTime
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1EchoTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_EchoDepth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1EchoDepth
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_EchoDepth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1EchoDepth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_ModulationTime
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1ModulationTime
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_ModulationTime
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1ModulationTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_ModulationDepth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1ModulationDepth
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_ModulationDepth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1ModulationDepth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_AirAbsorptionHF
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1AirAbsorptionHF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_AirAbsorptionHF
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1AirAbsorptionHF
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_HFReference
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1HFReference
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_HFReference
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1HFReference
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_LFReference
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1LFReference
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_LFReference
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1LFReference
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_RoomRolloffFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1RoomRolloffFactor
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_RoomRolloffFactor
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1RoomRolloffFactor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_Diffusion
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1Diffusion
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_Diffusion
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1Diffusion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_Density
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1Density
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_Density
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1Density
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_PROPERTIES_Flags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1PROPERTIES_1Flags
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_PROPERTIES_Flags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1PROPERTIES_1Flags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    new_FSOUND_REVERB_PROPERTIES
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_new_1FSOUND_1REVERB_1PROPERTIES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    delete_FSOUND_REVERB_PROPERTIES
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_delete_1FSOUND_1REVERB_1PROPERTIES
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_OFF
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1OFF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_GENERIC
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1GENERIC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_PADDEDCELL
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1PADDEDCELL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_ROOM
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1ROOM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_BATHROOM
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1BATHROOM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_LIVINGROOM
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1LIVINGROOM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_STONEROOM
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1STONEROOM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_AUDITORIUM
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1AUDITORIUM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_CONCERTHALL
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1CONCERTHALL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_CAVE
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1CAVE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_ARENA
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1ARENA
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_HANGAR
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1HANGAR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_CARPETTEDHALLWAY
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1CARPETTEDHALLWAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_HALLWAY
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1HALLWAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_STONECORRIDOR
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1STONECORRIDOR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_ALLEY
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1ALLEY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_FOREST
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1FOREST
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_CITY
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1CITY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_MOUNTAINS
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1MOUNTAINS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_QUARRY
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1QUARRY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_PLAIN
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1PLAIN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_PARKINGLOT
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1PARKINGLOT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_SEWERPIPE
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1SEWERPIPE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_UNDERWATER
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1UNDERWATER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_DRUGGED
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1DRUGGED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_DIZZY
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1DIZZY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_PSYCHOTIC
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1PSYCHOTIC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_PS2_ROOM
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1PS2_1ROOM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_PS2_STUDIO_A
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1PS2_1STUDIO_1A
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_PS2_STUDIO_B
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1PS2_1STUDIO_1B
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_PS2_STUDIO_C
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1PS2_1STUDIO_1C
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_PS2_HALL
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1PS2_1HALL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_PS2_SPACE
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1PS2_1SPACE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_PS2_ECHO
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1PS2_1ECHO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_PS2_DELAY
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1PS2_1DELAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_PRESET_PS2_PIPE
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1PRESET_1PS2_1PIPE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_Direct
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1Direct
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_Direct
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1Direct
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_DirectHF
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1DirectHF
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_DirectHF
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1DirectHF
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_Room
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1Room
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_Room
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1Room
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_RoomHF
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1RoomHF
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_RoomHF
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1RoomHF
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_Obstruction
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1Obstruction
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_Obstruction
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1Obstruction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_ObstructionLFRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1ObstructionLFRatio
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_ObstructionLFRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1ObstructionLFRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_Occlusion
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1Occlusion
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_Occlusion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1Occlusion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_OcclusionLFRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1OcclusionLFRatio
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_OcclusionLFRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1OcclusionLFRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_OcclusionRoomRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1OcclusionRoomRatio
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_OcclusionRoomRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1OcclusionRoomRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_OcclusionDirectRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1OcclusionDirectRatio
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_OcclusionDirectRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1OcclusionDirectRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_Exclusion
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1Exclusion
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_Exclusion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1Exclusion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_ExclusionLFRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1ExclusionLFRatio
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_ExclusionLFRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1ExclusionLFRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_OutsideVolumeHF
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1OutsideVolumeHF
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_OutsideVolumeHF
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1OutsideVolumeHF
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_DopplerFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1DopplerFactor
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_DopplerFactor
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1DopplerFactor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_RolloffFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1RolloffFactor
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_RolloffFactor
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1RolloffFactor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_RoomRolloffFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1RoomRolloffFactor
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_RoomRolloffFactor
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1RoomRolloffFactor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_AirAbsorptionFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1AirAbsorptionFactor
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_AirAbsorptionFactor
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1AirAbsorptionFactor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    set_FSOUND_REVERB_CHANNELPROPERTIES_Flags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_set_1FSOUND_1REVERB_1CHANNELPROPERTIES_1Flags
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_REVERB_CHANNELPROPERTIES_Flags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1REVERB_1CHANNELPROPERTIES_1Flags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    new_FSOUND_REVERB_CHANNELPROPERTIES
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_new_1FSOUND_1REVERB_1CHANNELPROPERTIES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    delete_FSOUND_REVERB_CHANNELPROPERTIES
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_delete_1FSOUND_1REVERB_1CHANNELPROPERTIES
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_TOC_TAG_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1TOC_1TAG_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_TOC_TAG_numtracks
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1TOC_1TAG_1numtracks
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_TOC_TAG_min
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1TOC_1TAG_1min
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_TOC_TAG_sec
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1TOC_1TAG_1sec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    get_FSOUND_TOC_TAG_frame
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_get_1FSOUND_1TOC_1TAG_1frame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    new_FSOUND_TOC_TAG
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_new_1FSOUND_1TOC_1TAG
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Structures_StructureJNI
 * Method:    delete_FSOUND_TOC_TAG
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Structures_StructureJNI_delete_1FSOUND_1TOC_1TAG
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
