/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_Fmod_FmodJNI */

#ifndef _Included_org_jouvieje_Fmod_FmodJNI
#define _Included_org_jouvieje_Fmod_FmodJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_Eject
 * Signature: (C)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1Eject
  (JNIEnv *, jclass, jchar);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    get_PLATFORM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_get_1PLATFORM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetOutput
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetOutput
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetDriver
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetDriver
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetMixer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetMixer
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetBufferSize
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetBufferSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetHWND
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetHWND
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetMinHardwareChannels
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetMinHardwareChannels
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetMaxHardwareChannels
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetMaxHardwareChannels
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetMemorySystem
 * Signature: (Ljava/nio/ByteBuffer;IILorg/jouvieje/Fmod/Callbacks/FSOUND_ALLOCCALLBACK;Lorg/jouvieje/Fmod/Callbacks/FSOUND_REALLOCCALLBACK;Lorg/jouvieje/Fmod/Callbacks/FSOUND_FREECALLBACK;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetMemorySystem
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Init
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Init
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Close
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Update
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetSpeakerMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetSpeakerMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetSFXMasterVolume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetSFXMasterVolume
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetPanSeperation
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetPanSeperation
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_File_SetCallbacks
 * Signature: (Lorg/jouvieje/Fmod/Callbacks/FSOUND_OPENCALLBACK;Lorg/jouvieje/Fmod/Callbacks/FSOUND_CLOSECALLBACK;Lorg/jouvieje/Fmod/Callbacks/FSOUND_READCALLBACK;Lorg/jouvieje/Fmod/Callbacks/FSOUND_SEEKCALLBACK;Lorg/jouvieje/Fmod/Callbacks/FSOUND_TELLCALLBACK;)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1File_1SetCallbacks
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetError
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetVersion
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetOutput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetOutput
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetOutputHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetOutputHandle
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetDriver
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetDriver
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetMixer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetMixer
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetNumDrivers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetNumDrivers
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetDriverName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetDriverName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetDriverCaps
 * Signature: (I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetDriverCaps__I_3I
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetDriverCaps
 * Signature: (ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetDriverCaps__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetOutputRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetOutputRate
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetMaxChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetMaxChannels
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetMaxSamples
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetMaxSamples
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetSpeakerMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetSpeakerMode
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetSFXMasterVolume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetSFXMasterVolume
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetNumHWChannels
 * Signature: ([I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetNumHWChannels___3I_3I_3I
  (JNIEnv *, jclass, jintArray, jintArray, jintArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetNumHWChannels
 * Signature: (Ljava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetNumHWChannels__Ljava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetChannelsPlaying
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetChannelsPlaying
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetCPUUsage
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetCPUUsage
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetMemoryStats
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetMemoryStats___3I_3I
  (JNIEnv *, jclass, jintArray, jintArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetMemoryStats
 * Signature: (Ljava/nio/IntBuffer;ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetMemoryStats__Ljava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_Load
 * Signature: (ILjava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1Load__ILjava_lang_String_2III
  (JNIEnv *, jclass, jint, jstring, jint, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_Load
 * Signature: (ILjava/nio/ByteBuffer;IIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1Load__ILjava_nio_ByteBuffer_2IIII
  (JNIEnv *, jclass, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_Alloc
 * Signature: (IIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1Alloc
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_Free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1Free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_Upload
 * Signature: (JLjava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1Upload
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_Lock
 * Signature: (JIILorg/jouvieje/Fmod/Misc/Pointer;Lorg/jouvieje/Fmod/Misc/Pointer;[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1Lock__JIILorg_jouvieje_Fmod_Misc_Pointer_2Lorg_jouvieje_Fmod_Misc_Pointer_2_3I_3I
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jobject, jintArray, jintArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_Lock
 * Signature: (JIILorg/jouvieje/Fmod/Misc/Pointer;Lorg/jouvieje/Fmod/Misc/Pointer;Ljava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1Lock__JIILorg_jouvieje_Fmod_Misc_Pointer_2Lorg_jouvieje_Fmod_Misc_Pointer_2Ljava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jobject, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_Unlock
 * Signature: (JJJII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1Unlock__JJJII
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_Unlock
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1Unlock__JLjava_nio_ByteBuffer_2ILjava_nio_ByteBuffer_2III
  (JNIEnv *, jclass, jlong, jobject, jint, jobject, jint, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_SetMode
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1SetMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_SetLoopPoints
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1SetLoopPoints
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_SetDefaults
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1SetDefaults
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_SetDefaultsEx
 * Signature: (JIIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1SetDefaultsEx
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_SetMinMaxDistance
 * Signature: (JFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1SetMinMaxDistance
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_SetMaxPlaybacks
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1SetMaxPlaybacks
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_Get
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1Get
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_GetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1GetName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_GetLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1GetLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_GetLoopPoints
 * Signature: (J[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1GetLoopPoints__J_3I_3I
  (JNIEnv *, jclass, jlong, jintArray, jintArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_GetLoopPoints
 * Signature: (JLjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1GetLoopPoints__JLjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_GetDefaults
 * Signature: (J[I[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1GetDefaults__J_3I_3I_3I_3I
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_GetDefaults
 * Signature: (JLjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1GetDefaults__JLjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jobject, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_GetDefaultsEx
 * Signature: (J[I[I[I[I[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1GetDefaultsEx__J_3I_3I_3I_3I_3I_3I_3I
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_GetDefaultsEx
 * Signature: (JLjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1GetDefaultsEx__JLjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_GetMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1GetMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_GetMinMaxDistance
 * Signature: (J[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1GetMinMaxDistance__J_3F_3F
  (JNIEnv *, jclass, jlong, jfloatArray, jfloatArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Sample_GetMinMaxDistance
 * Signature: (JLjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Sample_1GetMinMaxDistance__JLjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jlong, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_PlaySound
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1PlaySound
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_PlaySoundEx
 * Signature: (IJJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1PlaySoundEx
  (JNIEnv *, jclass, jint, jlong, jlong, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_StopSound
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1StopSound
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetFrequency
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetFrequency
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetVolume
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetVolume
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetVolumeAbsolute
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetVolumeAbsolute
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetPan
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetPan
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetSurround
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetSurround
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetMute
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetMute
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetPriority
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetPriority
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetReserved
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetReserved
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetPaused
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetPaused
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetLoopMode
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetLoopMode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_SetCurrentPosition
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1SetCurrentPosition
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_SetAttributes
 * Signature: (I[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1SetAttributes__I_3F_3F
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_SetAttributes
 * Signature: (ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1SetAttributes__ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_SetMinMaxDistance
 * Signature: (IFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1SetMinMaxDistance
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_IsPlaying
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1IsPlaying
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetFrequency
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetFrequency
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetVolume
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetVolume
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetAmplitude
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetAmplitude
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetPan
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetPan
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetSurround
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetSurround
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetMute
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetMute
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetPriority
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetPriority
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetReserved
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetReserved
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetPaused
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetPaused
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetLoopMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetLoopMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetCurrentPosition
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetCurrentPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetCurrentSample
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetCurrentSample
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetCurrentLevels
 * Signature: (I[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetCurrentLevels__I_3F_3F
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetCurrentLevels
 * Signature: (ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetCurrentLevels__ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetNumSubChannels
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetNumSubChannels
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_GetSubChannel
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1GetSubChannel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_GetAttributes
 * Signature: (I[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1GetAttributes__I_3F_3F
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_GetAttributes
 * Signature: (ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1GetAttributes__ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_GetMinMaxDistance
 * Signature: (I[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1GetMinMaxDistance__I_3F_3F
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_GetMinMaxDistance
 * Signature: (ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1GetMinMaxDistance__ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_Listener_SetAttributes
 * Signature: ([F[FFFFFFF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1Listener_1SetAttributes___3F_3FFFFFFF
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_Listener_SetAttributes
 * Signature: (Ljava/nio/FloatBuffer;ILjava/nio/FloatBuffer;IFFFFFF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1Listener_1SetAttributes__Ljava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2IFFFFFF
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_Listener_GetAttributes
 * Signature: ([F[F[F[F[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1Listener_1GetAttributes___3F_3F_3F_3F_3F_3F_3F_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_Listener_GetAttributes
 * Signature: (Ljava/nio/FloatBuffer;ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1Listener_1GetAttributes__Ljava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_Listener_SetCurrent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1Listener_1SetCurrent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_SetDopplerFactor
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1SetDopplerFactor
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_SetDistanceFactor
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1SetDistanceFactor
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_3D_SetRolloffFactor
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_13D_1SetRolloffFactor
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_FX_Enable
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1FX_1Enable
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_FX_Disable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1FX_1Disable
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_FX_SetChorus
 * Signature: (IFFFFIFI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1FX_1SetChorus
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_FX_SetCompressor
 * Signature: (IFFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1FX_1SetCompressor
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_FX_SetDistortion
 * Signature: (IFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1FX_1SetDistortion
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_FX_SetEcho
 * Signature: (IFFFFZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1FX_1SetEcho
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_FX_SetFlanger
 * Signature: (IFFFFIFI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1FX_1SetFlanger
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_FX_SetGargle
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1FX_1SetGargle
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_FX_SetI3DL2Reverb
 * Signature: (IIIFFFIFIFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1FX_1SetI3DL2Reverb
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jfloat, jint, jfloat, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_FX_SetParamEQ
 * Signature: (IFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1FX_1SetParamEQ
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_FX_SetWavesReverb
 * Signature: (IFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1FX_1SetWavesReverb
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_SetBufferSize
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1SetBufferSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Open
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Open__Ljava_lang_String_2III
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Open
 * Signature: (Ljava/nio/ByteBuffer;IIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Open__Ljava_nio_ByteBuffer_2IIII
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Create
 * Signature: (Lorg/jouvieje/Fmod/Callbacks/FSOUND_STREAMCALLBACK;IIIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Create
  (JNIEnv *, jclass, jobject, jint, jint, jint, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Close
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Play
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Play
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_PlayEx
 * Signature: (IJJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1PlayEx
  (JNIEnv *, jclass, jint, jlong, jlong, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Stop
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_SetPosition
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1SetPosition
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetPosition
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_SetTime
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1SetTime
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetTime
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetLengthMs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetLengthMs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_SetMode
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1SetMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_SetLoopPoints
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1SetLoopPoints
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_SetLoopCount
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1SetLoopCount
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetOpenState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetOpenState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetSample
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetSample
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_CreateDSP
 * Signature: (JLorg/jouvieje/Fmod/Callbacks/FSOUND_DSPCALLBACK;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1CreateDSP
  (JNIEnv *, jclass, jlong, jobject, jint, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_SetEndCallback
 * Signature: (JLorg/jouvieje/Fmod/Callbacks/FSOUND_STREAMCALLBACK;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1SetEndCallback
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_SetSyncCallback
 * Signature: (JLorg/jouvieje/Fmod/Callbacks/FSOUND_STREAMCALLBACK;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1SetSyncCallback
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_AddSyncPoint
 * Signature: (JILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1AddSyncPoint
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_DeleteSyncPoint
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1DeleteSyncPoint
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetNumSyncPoints
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetNumSyncPoints
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetSyncPoint
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetSyncPoint
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetSyncPointInfo
 * Signature: (J[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetSyncPointInfo__J_3I
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetSyncPointInfo
 * Signature: (JLjava/nio/IntBuffer;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetSyncPointInfo__JLjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_SetSubStream
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1SetSubStream
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetNumSubStreams
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetNumSubStreams
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_SetSubStreamSentence
 * Signature: (J[II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1SetSubStreamSentence__J_3II
  (JNIEnv *, jclass, jlong, jintArray, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_SetSubStreamSentence
 * Signature: (JLjava/nio/IntBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1SetSubStreamSentence__JLjava_nio_IntBuffer_2II
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetNumTagFields
 * Signature: (J[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetNumTagFields__J_3I
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetNumTagFields
 * Signature: (JLjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetNumTagFields__JLjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetTagField
 * Signature: (JI[ILorg/jouvieje/Fmod/Misc/Pointer;Lorg/jouvieje/Fmod/Misc/Pointer;[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetTagField__JI_3ILorg_jouvieje_Fmod_Misc_Pointer_2Lorg_jouvieje_Fmod_Misc_Pointer_2_3I
  (JNIEnv *, jclass, jlong, jint, jintArray, jobject, jobject, jintArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_GetTagField
 * Signature: (JILjava/nio/IntBuffer;ILorg/jouvieje/Fmod/Misc/Pointer;Lorg/jouvieje/Fmod/Misc/Pointer;Ljava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1GetTagField__JILjava_nio_IntBuffer_2ILorg_jouvieje_Fmod_Misc_Pointer_2Lorg_jouvieje_Fmod_Misc_Pointer_2Ljava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jint, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_FindTagField
 * Signature: (JILjava/lang/String;Lorg/jouvieje/Fmod/Misc/Pointer;[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1FindTagField__JILjava_lang_String_2Lorg_jouvieje_Fmod_Misc_Pointer_2_3I
  (JNIEnv *, jclass, jlong, jint, jstring, jobject, jintArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_FindTagField
 * Signature: (JILjava/lang/String;Lorg/jouvieje/Fmod/Misc/Pointer;Ljava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1FindTagField__JILjava_lang_String_2Lorg_jouvieje_Fmod_Misc_Pointer_2Ljava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jint, jstring, jobject, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Net_SetProxy
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Net_1SetProxy
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Net_SetTimeout
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Net_1SetTimeout
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Net_GetLastServerStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Net_1GetLastServerStatus
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Net_SetBufferProperties
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Net_1SetBufferProperties
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Net_GetBufferProperties
 * Signature: ([I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Net_1GetBufferProperties___3I_3I_3I
  (JNIEnv *, jclass, jintArray, jintArray, jintArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Net_GetBufferProperties
 * Signature: (Ljava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Net_1GetBufferProperties__Ljava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Net_SetMetadataCallback
 * Signature: (JLorg/jouvieje/Fmod/Callbacks/FSOUND_METADATACALLBACK;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Net_1SetMetadataCallback
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Net_GetStatus
 * Signature: (J[I[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Net_1GetStatus__J_3I_3I_3I_3I
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Stream_Net_GetStatus
 * Signature: (JLjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Stream_1Net_1GetStatus__JLjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jobject, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_Play
 * Signature: (CI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1Play
  (JNIEnv *, jclass, jchar, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_SetPlayMode
 * Signature: (CB)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1SetPlayMode
  (JNIEnv *, jclass, jchar, jbyte);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_Stop
 * Signature: (C)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1Stop
  (JNIEnv *, jclass, jchar);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_SetPaused
 * Signature: (CZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1SetPaused
  (JNIEnv *, jclass, jchar, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_SetVolume
 * Signature: (CI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1SetVolume
  (JNIEnv *, jclass, jchar, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_SetTrackTime
 * Signature: (CI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1SetTrackTime
  (JNIEnv *, jclass, jchar, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_GetPaused
 * Signature: (C)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1GetPaused
  (JNIEnv *, jclass, jchar);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_GetTrack
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1GetTrack
  (JNIEnv *, jclass, jchar);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_GetNumTracks
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1GetNumTracks
  (JNIEnv *, jclass, jchar);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_GetVolume
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1GetVolume
  (JNIEnv *, jclass, jchar);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_OpenTray
 * Signature: (CZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1OpenTray
  (JNIEnv *, jclass, jchar, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_GetTrackLength
 * Signature: (CI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1GetTrackLength
  (JNIEnv *, jclass, jchar, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_CD_GetTrackTime
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1CD_1GetTrackTime
  (JNIEnv *, jclass, jchar);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_Create
 * Signature: (Lorg/jouvieje/Fmod/Callbacks/FSOUND_DSPCALLBACK;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1Create
  (JNIEnv *, jclass, jobject, jint, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_Free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1Free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_SetPriority
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1SetPriority
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_GetPriority
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1GetPriority
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_SetActive
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1SetActive
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_GetActive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1GetActive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_GetClearUnit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1GetClearUnit
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_GetSFXUnit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1GetSFXUnit
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_GetMusicUnit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1GetMusicUnit
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_GetFFTUnit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1GetFFTUnit
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_GetClipAndCopyUnit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1GetClipAndCopyUnit
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_MixBuffers
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1MixBuffers
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_ClearMixBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1ClearMixBuffer
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_GetBufferLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1GetBufferLength
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_GetBufferLengthTotal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1GetBufferLengthTotal
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_DSP_GetSpectrum
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1DSP_1GetSpectrum
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Reverb_SetProperties
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Reverb_1SetProperties
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Reverb_GetProperties
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Reverb_1GetProperties
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Reverb_SetChannelProperties
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Reverb_1SetChannelProperties
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Reverb_GetChannelProperties
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Reverb_1GetChannelProperties
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Record_SetDriver
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Record_1SetDriver
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Record_GetNumDrivers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Record_1GetNumDrivers
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Record_GetDriverName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Record_1GetDriverName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Record_GetDriver
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Record_1GetDriver
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Record_StartSample
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Record_1StartSample
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Record_Stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Record_1Stop
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FSOUND_Record_GetPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FSOUND_1Record_1GetPosition
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_LoadSong
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1LoadSong
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_LoadSongEx
 * Signature: (Ljava/lang/String;III[II)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1LoadSongEx__Ljava_lang_String_2III_3II
  (JNIEnv *, jclass, jstring, jint, jint, jint, jintArray, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_LoadSongEx
 * Signature: (Ljava/lang/String;IIILjava/nio/IntBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1LoadSongEx__Ljava_lang_String_2IIILjava_nio_IntBuffer_2II
  (JNIEnv *, jclass, jstring, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_LoadSongEx
 * Signature: (Ljava/nio/ByteBuffer;IIII[II)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1LoadSongEx__Ljava_nio_ByteBuffer_2IIII_3II
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jintArray, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_LoadSongEx
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/IntBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1LoadSongEx__Ljava_nio_ByteBuffer_2IIIILjava_nio_IntBuffer_2II
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetOpenState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetOpenState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_FreeSong
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1FreeSong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_PlaySong
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1PlaySong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_StopSong
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1StopSong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_StopAllSongs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1StopAllSongs
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_SetZxxCallback
 * Signature: (JLorg/jouvieje/Fmod/Callbacks/FMUSIC_CALLBACK;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1SetZxxCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_SetRowCallback
 * Signature: (JLorg/jouvieje/Fmod/Callbacks/FMUSIC_CALLBACK;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1SetRowCallback
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_SetOrderCallback
 * Signature: (JLorg/jouvieje/Fmod/Callbacks/FMUSIC_CALLBACK;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1SetOrderCallback
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_SetInstCallback
 * Signature: (JLorg/jouvieje/Fmod/Callbacks/FMUSIC_CALLBACK;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1SetInstCallback
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_SetSample
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1SetSample
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_SetUserData
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1SetUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_OptimizeChannels
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1OptimizeChannels
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_SetReverb
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1SetReverb
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_SetLooping
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1SetLooping
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_SetOrder
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1SetOrder
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_SetPaused
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1SetPaused
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_SetMasterVolume
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1SetMasterVolume
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_SetMasterSpeed
 * Signature: (JF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1SetMasterSpeed
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_SetPanSeperation
 * Signature: (JF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1SetPanSeperation
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetNumOrders
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetNumOrders
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetNumPatterns
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetNumPatterns
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetNumInstruments
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetNumInstruments
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetNumSamples
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetNumSamples
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetNumChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetNumChannels
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetSample
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetSample
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetPatternLength
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetPatternLength
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_IsFinished
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1IsFinished
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_IsPlaying
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1IsPlaying
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetMasterVolume
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetMasterVolume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetGlobalVolume
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetGlobalVolume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetOrder
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetOrder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetPattern
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetPattern
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetSpeed
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetSpeed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetBPM
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetBPM
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetRow
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetRow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetPaused
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetPaused
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetTime
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetRealChannel
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetRealChannel
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMUSIC_GetUserData
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMUSIC_1GetUserData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_FmodJNI
 * Method:    FMOD_ErrorString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_Fmod_FmodJNI_FMOD_1ErrorString
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
