/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_Fmod_InitJNI */

#ifndef _Included_org_jouvieje_Fmod_InitJNI
#define _Included_org_jouvieje_Fmod_InitJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_Fmod_InitJNI
 * Method:    get_PLATFORM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_Fmod_InitJNI_get_1PLATFORM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_InitJNI
 * Method:    attachJavaVM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_InitJNI_attachJavaVM
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
