/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_Fmod_Misc_PointerUtilsJNI */

#ifndef _Included_org_jouvieje_Fmod_Misc_PointerUtilsJNI
#define _Included_org_jouvieje_Fmod_Misc_PointerUtilsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_Fmod_Misc_PointerUtilsJNI
 * Method:    Pointer_toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_Fmod_Misc_PointerUtilsJNI_Pointer_1toString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Misc_PointerUtilsJNI
 * Method:    new_ObjectPointer
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_Fmod_Misc_PointerUtilsJNI_new_1ObjectPointer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jouvieje_Fmod_Misc_PointerUtilsJNI
 * Method:    get_ObjectPointer
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_jouvieje_Fmod_Misc_PointerUtilsJNI_get_1ObjectPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_Fmod_Misc_PointerUtilsJNI
 * Method:    set_ObjectPointer
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Misc_PointerUtilsJNI_set_1ObjectPointer
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_Fmod_Misc_PointerUtilsJNI
 * Method:    delete_ObjectPointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_Fmod_Misc_PointerUtilsJNI_delete_1ObjectPointer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
