/* DO NOT EDIT THIS FILE - it is machine generated */
#include "Includes.h"
/* Header for class org_jouvieje_Fmod_Defines_DefineJNI */

#ifndef _Included_org_jouvieje_Fmod_Defines_DefineJNI
#define _Included_org_jouvieje_Fmod_Defines_DefineJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_Fmod_Defines_DefineJNI
 * Method:    get_FMOD_VERSION
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Defines_DefineJNI_get_1FMOD_1VERSION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_Fmod_Defines_DefineJNI
 * Method:    get_NATIVEFMOD_LIBRARY_VERSION
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_Fmod_Defines_DefineJNI_get_1NATIVEFMOD_1LIBRARY_1VERSION
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
